# Generated by Django 2.1.7 on 2019-06-12 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WordTutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='user',
            field=models.ManyToManyField(through='WordTutor.userbook', to='WordTutor.userinfo'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='word',
            field=models.ManyToManyField(to='WordTutor.wordinfo'),
        ),
        migrations.AddField(
            model_name='noteinfo',
            name='word',
            field=models.ManyToManyField(to='WordTutor.wordinfo'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='bookid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WordTutor.bookinfo'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WordTutor.userinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together=set(),
        ),
    ]
