# Generated by Django 2.1.7 on 2019-06-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordTutor', '0003_auto_20190612_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='wordnum',
            field=models.IntegerField(verbose_name='单词数量'),
        ),
        migrations.AlterField(
            model_name='noteinfo',
            name='finishnum',
            field=models.IntegerField(verbose_name='完成数量'),
        ),
        migrations.AlterField(
            model_name='noteinfo',
            name='wordnum',
            field=models.IntegerField(verbose_name='单词数量'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='finishnum',
            field=models.IntegerField(verbose_name='用户完成数量'),
        ),
    ]
