# Generated by Django 2.1.7 on 2019-06-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordTutor', '0004_auto_20190612_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
    ]
